server:
  port: 6002

eureka:
  instance:
    hostname: eureka6002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/
  server:
    enable-self-preservation: false #开发阶段禁用自我保护机制