server:
  port: 6001                # 服务端口

eureka:
  instance:
#    hostname: localhost 单机配置
    hostname: eureka6001.com
  client:
    registerWithEureka: false       #服务注册，false表示不将自己注册到Eureka中
    fetchRegistry: false            #服务发现，false表示自己不从Eureka中服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自 己（如果不配置则默认本机8761端口）
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 单机配置
      defaultZone: http://eureka6002.com:6002/eureka/
  server:
    enable-self-preservation: false #开发阶段禁用自我保护机制